# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'FinalExam' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'SDWebImage'
pod 'SwiftyJSON'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/Core'




  # Pods for FinalExam

end
